# nuc01-dynamic.yaml
network:
    version: 2
    renderer: NetworkManager
    ethernets:
        ethernet0:
            match:
                macaddress: 94:c6:91:a3:ac:12
            set-name: ethernet0
            dhcp4: true
            dhcp6: true
            accept-ra: true
            ipv6-address-token: "::3"
    wifis:
        wifi0:
            match:
                macaddress: c0:b6:f9:cd:d0:f7
            set-name: wifi0
            access-points:
                "network_ssid_name":
                    password: "**********"
            activation-mode: manual
